resources:
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
cch:
  background: 'rgba(46, 46, 46, 0.5)'
  clock_am_pm: false
  clock_date: true
  clock_format: '24'
  options: clock
  swipe: true
  swipe_animate: fade
  swipe_prevent_default: true
custom_header:
  chevrons: false
  compact_mode: true
title: Home
views:
  - badges: []
    cards:
      - cards:
          - cards:
              - aspect_ratio: 50%
                entity: camera.kitchencam
                show_name: true
                show_state: false
                tap_action:
                  action: navigate
                  navigation_path: 'https://home.sbhost.co.uk/lovelace/kitchen'
                type: picture-entity
              - aspect_ratio: 50%
                entity: camera.loungecam
                show_name: true
                show_state: false
                tap_action:
                  action: navigate
                  navigation_path: 'https://home.sbhost.co.uk/lovelace/lounge'
                type: picture-entity
            type: horizontal-stack
        type: vertical-stack
      - cards:
          - cards:
              - entity: light.bathroom
                name: Bathroom
                type: light
              - entity: light.bedroom
                name: Bedroom
                type: light
              - entity: light.study
                name: Study
                type: light
            type: horizontal-stack
          - cards:
              - entity: light.hall
                name: Hall
                type: light
              - entity: light.kitchen
                name: Kitchen
                type: light
              - entity: light.lounge
                name: Lounge
                type: light
            type: horizontal-stack
          - cards:
              - entity: light.toilet
                name: Toilet
                type: light
              - entity: light.entrance
                name: Entrance
                type: light
            type: horizontal-stack
        type: vertical-stack
      - cards:
          - cards:
              - entity: climate.bathroom
                name: Bathroom
                type: thermostat
              - entity: climate.bedroom
                name: Bedroom
                type: thermostat
            type: horizontal-stack
          - cards:
              - entity: climate.study
                name: Study
                type: thermostat
              - entity: climate.toilet
                name: Toilet
                type: thermostat
            type: horizontal-stack
          - entity: climate.heating
            name: Central
            type: thermostat
        type: vertical-stack
      - entities:
          - entity: sensor.people_home
          - entity: sensor.front_door_open
          - entity: person.laura_ward
          - entity: person.sebastian_burrell
          - entity: sensor.next_bin_collection
        type: entities
      - entity: media_player.bedroom_tv
        type: media-control
      - entity: media_player.shield
        type: media-control
      - entity: media_player.spotify_hankanman
        type: media-control
      - entity: weather.home
        type: 'custom:weather-card'
    icon: 'mdi:home'
    path: default_view
    title: Home
  - badges: []
    cards:
      - cards:
          - cards:
              - aspect_ratio: 50%
                camera_view: live
                entity: camera.kitchencam
                show_name: false
                show_state: false
                type: picture-entity
            type: horizontal-stack
          - cards:
              - color: auto
                name: < Back
                tap_action:
                  action: navigate
                  navigation_path: 'https://home.sbhost.co.uk/lovelace/default_view'
                type: 'custom:button-card'
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:fridge'
    panel: true
    path: kitchen
    title: Kitchen
  - badges: []
    cards:
      - cards:
          - cards:
              - aspect_ratio: 50%
                camera_view: live
                entity: camera.loungecam
                show_name: false
                show_state: false
                type: picture-entity
            type: horizontal-stack
          - cards:
              - color: auto
                name: < Back
                tap_action:
                  action: navigate
                  navigation_path: 'https://home.sbhost.co.uk/lovelace/default_view'
                type: 'custom:button-card'
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:sofa'
    panel: true
    path: lounge
    title: Lounge
  - badges: []
    cards:
      - cards:
          - cards:
              - aspect_ratio: 50%
                camera_view: live
                entity: camera.front_door
                show_name: false
                show_state: false
                type: picture-entity
            type: horizontal-stack
          - cards:
              - color: auto
                name: < Back
                tap_action:
                  action: navigate
                  navigation_path: 'https://home.sbhost.co.uk/lovelace/default_view'
                type: 'custom:button-card'
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:door'
    panel: true
    path: front_door
    title: Front Door
  - badges: []
    cards:
      - cards:
          - color_thresholds:
              - color: white
                value: 70
              - color: yellow
                value: 20
              - color: grey
                value: 10
            entities:
              - entity: sensor.study_luminance
                index: 0
            hours_to_show: 168
            icon: 'mdi:brightness-6'
            line_color: yellow
            points_per_hour: 2
            type: 'custom:mini-graph-card'
          - color_thresholds:
              - color: '#c0392b'
                value: 23
              - color: '#d35400'
                value: 21
              - color: '#1A89F5'
                value: 19
            entities:
              - entity: sensor.study_temperature
                index: 0
            hours_to_show: 168
            icon: 'mdi:thermometer'
            points_per_hour: 2
            type: 'custom:mini-graph-card'
            unit: °C
            title: Study
        type: vertical-stack
      - cards:
          - color_thresholds:
              - color: white
                value: 70
              - color: yellow
                value: 20
              - color: grey
                value: 10
            entities:
              - entity: sensor.bedroom_luminance
                index: 0
            hours_to_show: 168
            icon: 'mdi:brightness-6'
            line_color: yellow
            points_per_hour: 2
            type: 'custom:mini-graph-card'
          - color_thresholds:
              - color: '#c0392b'
                value: 23
              - color: '#d35400'
                value: 21
              - color: '#1A89F5'
                value: 19
            entities:
              - entity: sensor.bedroom_temp
                index: 0
            hours_to_show: 168
            icon: 'mdi:thermometer'
            points_per_hour: 2
            type: 'custom:mini-graph-card'
            unit: °C
            title: Bedroom
        type: vertical-stack
      - cards:
          - color_thresholds:
              - color: white
                value: 70
              - color: yellow
                value: 20
              - color: grey
                value: 10
            entities:
              - entity: sensor.toilet_luminance
                index: 0
            hours_to_show: 168
            icon: 'mdi:brightness-6'
            line_color: yellow
            points_per_hour: 2
            type: 'custom:mini-graph-card'
          - color_thresholds:
              - color: '#c0392b'
                value: 23
              - color: '#d35400'
                value: 21
              - color: '#1A89F5'
                value: 19
            entities:
              - entity: sensor.toilet_temperature
                index: 0
            hours_to_show: 168
            icon: 'mdi:thermometer'
            points_per_hour: 2
            type: 'custom:mini-graph-card'
            unit: °C
            title: Toilet
        type: vertical-stack
      - cards:
          - color_thresholds:
              - color: white
                value: 70
              - color: yellow
                value: 20
              - color: grey
                value: 10
            entities:
              - entity: sensor.kitchen_luminance
                index: 0
            hours_to_show: 168
            icon: 'mdi:brightness-6'
            line_color: yellow
            points_per_hour: 2
            type: 'custom:mini-graph-card'
          - color_thresholds:
              - color: '#c0392b'
                value: 23
              - color: '#d35400'
                value: 21
              - color: '#1A89F5'
                value: 19
            entities:
              - entity: sensor.kitchen_temperature
                index: 0
            hours_to_show: 168
            icon: 'mdi:thermometer'
            points_per_hour: 2
            type: 'custom:mini-graph-card'
            unit: °C
            title: Kitchen
        type: vertical-stack
      - cards:
          - color_thresholds:
              - color: white
                value: 70
              - color: yellow
                value: 20
              - color: grey
                value: 10
            entities:
              - entity: sensor.lounge_luminance
                index: 0
            hours_to_show: 168
            icon: 'mdi:brightness-6'
            line_color: yellow
            points_per_hour: 2
            type: 'custom:mini-graph-card'
          - color_thresholds:
              - color: '#c0392b'
                value: 23
              - color: '#d35400'
                value: 21
              - color: '#1A89F5'
                value: 19
            entities:
              - entity: sensor.lounge_temperature
                index: 0
            hours_to_show: 168
            icon: 'mdi:thermometer'
            points_per_hour: 2
            type: 'custom:mini-graph-card'
            unit: °C
            title: Lounge
        type: vertical-stack
      - cards:
          - color_thresholds:
              - color: white
                value: 70
              - color: yellow
                value: 20
              - color: grey
                value: 10
            entities:
              - entity: sensor.hall_luminance
                index: 0
            hours_to_show: 168
            icon: 'mdi:brightness-6'
            line_color: yellow
            points_per_hour: 2
            type: 'custom:mini-graph-card'
          - color_thresholds:
              - color: '#c0392b'
                value: 23
              - color: '#d35400'
                value: 21
              - color: '#1A89F5'
                value: 19
            entities:
              - entity: sensor.hall_temperature
                index: 0
            hours_to_show: 168
            icon: 'mdi:thermometer'
            points_per_hour: 2
            type: 'custom:mini-graph-card'
            unit: °C
            title: Hall
        type: vertical-stack
      - cards:
          - color_thresholds:
              - color: white
                value: 15
              - color: yellow
                value: 10
              - color: grey
                value: 5
            entities:
              - entity: sensor.bathroom_luminance
                index: 0
            hours_to_show: 168
            icon: 'mdi:brightness-6'
            line_color: yellow
            points_per_hour: 2
            type: 'custom:mini-graph-card'
          - color_thresholds:
              - color: '#c0392b'
                value: 23
              - color: '#d35400'
                value: 21
              - color: '#1A89F5'
                value: 19
            entities:
              - entity: sensor.bathroom_temperature
                index: 0
            hours_to_show: 168
            icon: 'mdi:thermometer'
            points_per_hour: 2
            type: 'custom:mini-graph-card'
            unit: °C
          - color_thresholds:
              - color: '#c0392b'
                value: 23
              - color: '#d35400'
                value: 21
              - color: '#1A89F5'
                value: 19
            entities:
              - entity: sensor.bathroom_relative_humidity
                index: 0
            hours_to_show: 168
            icon: 'mdi:thermometer'
            points_per_hour: 2
            type: 'custom:mini-graph-card'
            unit: '%'
            title: Bathroom
        type: vertical-stack
      - cards:
          - aggregate_func: max
            entities:
              - entity: sensor.gas_daily_usage
                index: 0
            group_by: date
            hours_to_show: 168
            icon: 'mdi:fire'
            line_color: orange
            name: Gas Consumption
            show:
              graph: bar
            type: 'custom:mini-graph-card'
          - aggregate_func: max
            entities:
              - entity: sensor.electricity_daily_usage
                index: 0
            group_by: date
            hours_to_show: 168
            icon: 'mdi:fire'
            line_color: '#1A89F5'
            name: Electricity Consumption
            show:
              graph: bar
            type: 'custom:mini-graph-card'
          - color_thresholds:
              - color: '#c0392b'
                value: 23
              - color: '#d35400'
                value: 21
              - color: '#1A89F5'
                value: 19
            entities:
              - entity: sensor.downstairs_temp
                index: 0
            hours_to_show: 168
            icon: 'mdi:thermometer'
            points_per_hour: 2
            type: 'custom:mini-graph-card'
            unit: °C
            title: House
        type: vertical-stack
    icon: 'mdi:chart-line'
    path: graphs
    title: Graphs
